spring:
  datasource:
    url: jdbc:mysql://localhost/forohub
    username: root
    password: 12345

server:
  error:
    include-stacktrace: never #para ocultar la informacion del error 'trace'

api:
  security.secret=${JWT_SECRET:12345}